name: go_here
description: GoHere

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  intl: ^0.16.0
  url_launcher: ^5.1.4
  carousel_slider: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  rxdart: ^0.22.2
  provider: ^3.1.0
  built_value: ^6.7.1
  build_runner: ^1.7.1
  built_value_generator: ^6.7.1

flutter:
  uses-material-design: true
